export const tempData = {
  home: [
    {
      id: '2546',
      lastName: 'Anthony',
      firstName: 'Carmelo',
      draft: '3rd overall pick, 2003 (Denver)',
      highlights:
        'Anthony, 35, holds career NBA averages of 24.0 points (44.9% FG, 34.7% 3-PT, 81.1% FT), 6.5 rebounds, 3.0 assists and 1.0 steals in 1,064 games (1,056 starts) over 16 seasons with Denver, New York, Oklahoma City and Houston.',
      twitter: 'carmeloanthony',
      instagram: 'carmeloanthony',
      number: '00',
      pointsPerGame: '20',
      reboundsPerGame: '10',
      assistsPerGame: '8',
      fieldGoalPercent: '65%',
      freeThrowPercent: '85%',
      threePointFieldGoal: '75%',
      stealsPerGame: '2',
      blocksPerGame: '1.5',
    },
    {
      id: '2772',
      lastName: 'Ariza',
      firstName: 'Trevor',
      twitter: 'trevorAriza',
      number: '8',
      pointsPerGame: '10',
      reboundsPerGame: '9',
      assistsPerGame: '7',
      fieldGoalPercent: '60%',
      freeThrowPercent: '75%',
      threePointFieldGoal: '55%',
      stealsPerGame: '1.2',
      blocksPerGame: '1.3',
    },
  ],
  visiting: [
    {
      id: '1629658',
      lastName: 'Hoard',
      firstName: 'Jaylen',
      draft: "Not picked in 2019-20 'draft'.",
      highlights: [''],
      twitter: '',
      instagram: '',
      number: 6,
      pointsPerGame: '10',
      reboundsPerGame: '9',
      assistsPerGame: '7',
      fieldGoalPercent: '60%',
      freeThrowPercent: '75%',
      threePointFieldGoal: '55%',
      stealsPerGame: '1.2',
      blocksPerGame: '1.3',
    },
    {
      id: '203918',
      lastName: 'Hood',
      firstName: 'Rodney',
      draft: '23rd pick, 2014 (Utah)',
      highlights:
        'Netted double figures in scoring in 11 of 27 games after being traded to the Trail Blazers on Feb. 4, 2019. Scored 25 points in Portland’s Game 6 win against the Nuggets in the 2019 Western Conference Semifinals. Ranked 10th in the NBA with an 88.4% mark from the foul line in 2018-19. A career 36.7% 3-point shooter, he has made 548 career 3-pointers entering 2019-20.',
      twitter: 'rodneyhood',
      instagram: 'hoodie5',
      number: '5',
      pointsPerGame: '10',
      reboundsPerGame: '9',
      assistsPerGame: '7',
      fieldGoalPercent: '60%',
      freeThrowPercent: '75%',
      threePointFieldGoal: '55%',
      stealsPerGame: '1.2',
      blocksPerGame: '1.3',
    },
  ],
};
