var testJsonObject = [
  {
    'id': '2546',
    'lastName': "Anthony",
    'firstName': "Carmelo",
    'draft': "3rd overall pick, 2003 (Denver)",
    'highlights':
      "Anthony, 35, holds career NBA averages of 24.0 points (44.9% FG, 34.7% 3-PT, 81.1% FT), 6.5 rebounds, 3.0 assists and 1.0 steals in 1,064 games (1,056 starts) over 16 seasons with Denver, New York, Oklahoma City and Houston.",
    'twitter': "carmeloanthony",
    'instagram': "carmeloanthony",
    'number': "00",
    'pointsPerGame': '20',
    'reboundsPerGame': '10',
    'assistsPerGame': '8',
    'fieldGoalPercent': '65%',
    'freeThrowPercent': '85%',
    'threePointFieldGoal': '75%',
    'stealsPerGame': '2',
    'blocksPerGame': '1.5',
  },
  {
    'id': '2772',
    'lastName': "Ariza",
    'firstName': 'Trevor',
    'twitter': "trevorAriza",
    'number': '8',
    'pointsPerGame': '10',
    'reboundsPerGame': '9',
    'assistsPerGame': '7',
    'fieldGoalPercent': '60%',
    'freeThrowPercent': '75%',
    'threePointFieldGoal': '55%',
    'stealsPerGame': '1.2',
    'blocksPerGame': '1.3',
  },
  {
    'id': '1629650',
    'lastName': "Brown",
    'firstName': 'Moses',
    'number': '4',
    'pointsPerGame': '12',
    'reboundsPerGame': '7',
    'assistsPerGame': '9',
    'fieldGoalPercent': '55%',
    'freeThrowPercent': '85%',
    'threePointFieldGoal': '95%',
    'stealsPerGame': '1.7',
    'blocksPerGame': '6.3',
  },
  {
    'id': '1628380',
    'lastName': "Collins",
    'firstName': "Zack",
    'draft': "10th pick, 2017 (Sacramento)",
    'qa':
      "Q: What was the first album you ever bought? A: Dark Horse - Nickelback. Q: Who was your favorite NBA player growing up? A:  LeBron James. Q: Who do you play as in Mario Kart? A: Mario. Q: What are your favorite shoes you’ve worn on the court? A: LeBron Soldier 10. Q: If you had to eat at one restaurant for the rest of your life, what would it be? A: Chipotle. Q: What is your favorite TV show? A: Game of Thrones. Q: What is your go-to karaoke song? A: Come Thru (Nothing Was The Same) - Drake. Q: If you could be any animal for a day, what would you choose? A: Lion. Q: What’s your favorite Thanksgiving food? A: Mashed Potatoes. Q: If a theme song played every time you entered a room, what would it be? A: Sweet Dreams - Marilyn Manson.",
    'highlights':
      "Averaged 6.6 points and scored in double figures 19 times in his second season with the Trail Blazers in 2018-19. Blocked 22 shots (8th in the NBA) during Portland’s run to the 2019 Western Conference Finals. Ranked 13th among NBA rookies in blocks (31), 18th in rebounds (221) and 23rd in 3-pointers (35) as a rookie in 2017-18. Led the West Coast Conference as a Gonzaga freshman in 2016-17 in field goal shooting and blocked shots.",
    'twitter': "zcollins_33",
    'instagram': "zachcollins_33",
    'number': '33',
    'pointsPerGame': '18',
    'reboundsPerGame': '10',
    'assistsPerGame': '5',
    'fieldGoalPercent': '64%',
    'freeThrowPercent': '66%',
    'threePointFieldGoal': '76%',
    'stealsPerGame': '1.5',
    'blocksPerGame': '1.8',
  },
  {
    'id': '1629117',
    'lastName': "Gabriel",
    'firstName': 'Wenyen',
    'twitter': "WenyenGabriel",
    'instagram': "WenyenGabriel",
    'number': '35',
    'pointsPerGame': '10',
    'reboundsPerGame': '9',
    'assistsPerGame': '7',
    'fieldGoalPercent': '60%',
    'freeThrowPercent': '75%',
    'threePointFieldGoal': '55%',
    'stealsPerGame': '1.2',
    'blocksPerGame': '1.3',
  },
  {
    'id': '1626209',
    'lastName': "Hezonja",
    'firstName': 'Mario',
    'draft': "5th pick, 2015 (Orlando)",
    'highlights':
      "Played four seasons with Orlando and New York after being selected by the Magic with the 5th overall pick in the 2015 NBA Draft. Averaged 8.8 points and a career-best 4.1 rebounds in 20.8 minutes with the Knicks during the 2018-19 season. Recorded a triple-double and then scored a career-high 30 points in back-to-back games April 5-7, 2019.",
    'twitter': "mariohezonja",
    'instagram': "supermariohezonja",
    'number': '44',
    'pointsPerGame': '10',
    'reboundsPerGame': '9',
    'assistsPerGame': '7',
    'fieldGoalPercent': '60%',
    'freeThrowPercent': '75%',
    'threePointFieldGoal': '55%',
    'stealsPerGame': '1.2',
    'blocksPerGame': '1.3',
  },
  {
    'id': '1629658',
    'lastName': "Hoard",
    'firstName': 'Jaylen',
    'draft': "Not picked in 2019-20 'draft'.",
    'highlights': [""],
    'twitter': "",
    'instagram': "",
    'number': 6,
    'pointsPerGame': '10',
    'reboundsPerGame': '9',
    'assistsPerGame': '7',
    'fieldGoalPercent': '60%',
    'freeThrowPercent': '75%',
    'threePointFieldGoal': '55%',
    'stealsPerGame': '1.2',
    'blocksPerGame': '1.3',
  },
  {
    'id': '203918',
    'lastName': "Hood",
    'firstName': 'Rodney',
    'draft': "23rd pick, 2014 (Utah)",
    'highlights':
      "Netted double figures in scoring in 11 of 27 games after being traded to the Trail Blazers on Feb. 4, 2019. Scored 25 points in Portland’s Game 6 win against the Nuggets in the 2019 Western Conference Semifinals. Ranked 10th in the NBA with an 88.4% mark from the foul line in 2018-19. A career 36.7% 3-point shooter, he has made 548 career 3-pointers entering 2019-20.",
    'twitter': "rodneyhood",
    'instagram': "hoodie5",
    'number': '5',
    'pointsPerGame': '10',
    'reboundsPerGame': '9',
    'assistsPerGame': '7',
    'fieldGoalPercent': '60%',
    'freeThrowPercent': '75%',
    'threePointFieldGoal': '55%',
    'stealsPerGame': '1.2',
    'blocksPerGame': '1.3',
  },
  {
    'id': '203081',
    'lastName': "Lillard",
    'firstName': "Damian",
    'draft': "6th pick, 2012 (Portland)",
    'highlights':
      "Earned NBA All-Star honors for the fourth time last season (2014, 2015, 2018, 2019). Named to the All-NBA Team four times (1st Team in 2017-18, 2nd Team in 2015-16 and 2018-19, 3rd Team in 2013-14). Portland’s franchise leader in 3-pointers (1,506) and ranks second in points (12,909) entering 2019-20. Third player in NBA history with 1,500 points and 400 assists in each of his first seven seasons (LeBron James, Oscar Robertson). Holds the team record for points in a game (59 vs. Utah, 4/8/17). Unanimously named the 2012-13 NBA Rookie of the Year.",
    'twitter': "Dame_Lillard",
    'instagram': "damianlillard",
    'number': '0',
    'pointsPerGame': '10',
    'reboundsPerGame': '9',
    'assistsPerGame': '7',
    'fieldGoalPercent': '60%',
    'freeThrowPercent': '75%',
    'threePointFieldGoal': '55%',
    'stealsPerGame': '1.2',
    'blocksPerGame': '1.3',
  },
  {
    'id': '1629642',
    'lastName': "Little",
    'firstName': 'Nassir',
    'highlights':
      "Averaged 9.8 points in just 18.2 minutes as a North Carolina freshman in 2018-19. Shot 47.8% FG and 77.0% FT in his lone season with the Tar Heels. Named a McDonald's All-American at the end of his high school career in Orlando. The first Trail Blazers player to be born in the 2000s.",
    'twitter': "2ez_nassie",
    'instagram': "nassir",
    'number': '9',
    'pointsPerGame': '10',
    'reboundsPerGame': '9',
    'assistsPerGame': '7',
    'fieldGoalPercent': '60%',
    'freeThrowPercent': '75%',
    'threePointFieldGoal': '55%',
    'stealsPerGame': '1.2',
    'blocksPerGame': '1.3',
  },
  {
    'id': '203468',
    'lastName': "McCollum",
    'firstName': 'CJ',
    'draft': "10th pick, 2013 (Portland)",
    'highlights':
      "Averaged more than 20 points in each of the past four years. Ranks second on Portland’s all-time list for 3-pointers made entering 2019-20 (823). Finished 7th in the NBA in field goals for three straight seasons (2015-18). Led the NBA in free throw shooting (91.2%) in 2016-17. Named the 2015-16 NBA Most Improved Player.",
    'twitter': "CJMcCollum",
    'instagram': "3jmccollum",
    'number': '3',
    'pointsPerGame': '10',
    'reboundsPerGame': '9',
    'assistsPerGame': '7',
    'fieldGoalPercent': '60%',
    'freeThrowPercent': '75%',
    'threePointFieldGoal': '55%',
    'stealsPerGame': '1.2',
    'blocksPerGame': '1.3',
  },
  {
    'id': '203994',
    'lastName': "Nurkić",
    'firstName': 'Jusuf',
    'draft': "16th pick, 2014 (Chicago)",
    'highlights':
      "Led the team in rebounds (10.4, 12th in NBA), blocks (1.4, 13th in NBA) and double-doubles (36, T-14th in NBA) in 2018-19. Posted 24 points, a career-high 23 rebounds, seven assists, five steals and five blocks at Sacramento on Jan. 1, becoming the first player in NBA history to record a five-by-five while having at least 20 points and 20 rebounds. Ranked 9th in the NBA with 243 offensive rebounds during the 2019-20 season. The only Trail Blazer to total 30+ points on 80% FG and 15+ rebounds in a game (3/28/17 vs. Denver).",
    'twitter': "bosnianbeast27",
    'instagram': "bosnianbeast27",
    'number': '27',
    'pointsPerGame': '10',
    'reboundsPerGame': '9',
    'assistsPerGame': '7',
    'fieldGoalPercent': '60%',
    'freeThrowPercent': '75%',
    'threePointFieldGoal': '55%',
    'stealsPerGame': '1.2',
    'blocksPerGame': '1.3',
  },
  {
    'id': '1629014',
    'lastName': "Simons",
    'firstName': 'Anfernee',
    'draft': "24th pick, 2018 (Portland)",
    'qa':
      "Q: What was the first album you ever bought? A: Chris Brown – Chris Brown. Q: Who was your favorite NBA player growing up? A: Wing Chun (type of martial arts). Q: Who do you play as in Mario Kart? A: Luigi. Q: What are your favorite shoes you’ve worn on the court? A: Kobe. Q: If you had to eat at one restaurant for the rest of your life, what would it be? A: Chick-Fil-A. Q: What is your favorite TV show? A: The Boondocks. Q: What is your go-to karaoke song? A: Doesn't do karaoke. Q: If you could be any animal for a day, what would you choose? A: Lion. Q: What’s your favorite Thanksgiving food? A: Mac & Cheese and Turkey. Q: If a theme song played every time you entered a room, what would it be? A: Star Wars Theme Song.",
    'highlights':
      "Became the second rookie in league history to have at least 37 points, six rebounds, nine assists and seven 3-pointers in Portland’s final game of the 2018-19 season vs. Sacramento. Averaged 22.4 points (54% FG, 45% 3-PT), 6.7 rebounds and 3.1 assists as a post-graduate at IMG Academy in 2017-18. As a senior at Edgewater High School in Orlando in 2016-17, averaged 23.8 points, 7.2 rebounds and 4.2 assists. Named after four-time NBA All-Star Anfernee “Penny” Hardaway.",
    'twitter': "AnferneeSimons",
    'instagram': "antsimons",
    'number': '1',
    'pointsPerGame': '10',
    'reboundsPerGame': '9',
    'assistsPerGame': '7',
    'fieldGoalPercent': '60%',
    'freeThrowPercent': '75%',
    'threePointFieldGoal': '55%',
    'stealsPerGame': '1.2',
    'blocksPerGame': '1.3',
  },
  {
    'id': '1628403',
    'lastName': "Swanigan",
    'firstName': 'Caleb',
    'twitter': "calebswanigan50",
    'instagram': "calebswanigan50",
    'number': '50',
    'pointsPerGame': '10',
    'reboundsPerGame': '9',
    'assistsPerGame': '7',
    'fieldGoalPercent': '60%',
    'freeThrowPercent': '75%',
    'threePointFieldGoal': '55%',
    'stealsPerGame': '1.2',
    'blocksPerGame': '1.3',
  },
  {
    'id': '1629018',
    'lastName': "Trent Jr.",
    'firstName': 'Gary',
    'draft': "37th pick, 2018 (Sacramento)",
    'highlights':
      "Scored a career-high 19 points on April 10, 2019 against the Kings. Averaged 14.5 points and 4.2 rebounds as a freshman at Duke in 2017-18. Broke J.J. Redick’s Duke freshman record with 97 3-pointers. Father, Gary Trent Sr., played his first two-plus seasons for Portland from 1995-98.",
    'twitter': "gtrentjr",
    'instagram': "gtrentjr",
    'number': '2',
    'pointsPerGame': '10',
    'reboundsPerGame': '9',
    'assistsPerGame': '7',
    'fieldGoalPercent': '60%',
    'freeThrowPercent': '75%',
    'threePointFieldGoal': '55%',
    'stealsPerGame': '1.2',
    'blocksPerGame': '1.3',
  },
  {
    'id': '202355',
    'lastName': "Whiteside",
    'firstName': 'Hassan',
    'draft': "33rd pick, 2010 (Sacramento)",
    'highlights':
      "Has appeared in 343 games during his six-year career with Miami and Sacramento, averaging 13.4 points, 11.4 rebounds and 2.3 blocks. Ranked 6th in the NBA in offensive rebounds (257) and 7th in blocked shots in 2017-18. Led the NBA with 14.1 rebounds per game in 2016-17 and 3.7 blocks per game in 2015-16. Named to the NBA All-Defensive Second Team after the 2015-16 season with Miami.",
    'twitter': "youngwhiteside",
    'instagram': "hassanwhiteside",
    'number': '21',
    'pointsPerGame': '10',
    'reboundsPerGame': '9',
    'assistsPerGame': '7',
    'fieldGoalPercent': '60%',
    'freeThrowPercent': '75%',
    'threePointFieldGoal': '55%',
    'stealsPerGame': '1.2',
    'blocksPerGame': '1.3',
  }
];

export default testJsonObject;