? ({
    "blazers": {
        "months": [
            {
                "monthName": "March",
                "monthVal": "mar"
            }
        ],
        "days": [
            {
                "dayName": "Friday",
                "dayVal": "fri",
                "dayType": false
            }
        ],
        "teams": [
            {
                "teamName": "Cleveland Cavaliers",
                "teamVal": "cavaliers"
            },
            {
                "teamName": "Dallas Mavericks",
                "teamVal": "mavericks"
            },
            {
                "teamName": "Denver Nuggets",
                "teamVal": "nuggets"
            },
            {
                "teamName": "Houston Rockets",
                "teamVal": "rockets"
            },
            {
                "teamName": "Los Angeles Clippers",
                "teamVal": "clippers"
            },
            {
                "teamName": "Memphis Grizzlies",
                "teamVal": "grizzlies"
            },
            {
                "teamName": "Minnesota Timberwolves",
                "teamVal": "timberwolves"
            },
            {
                "teamName": "Utah Jazz",
                "teamVal": "jazz"
            }
        ],
        "games": [
            {
                "gameNumber": "20TB34",
                "preseason": "0",
                "schedId": "",
                "playoff": "0",
                "schedSort": "20220311",
                "schedDay": "Friday",
                "schedDate": "March 11th, 2022",
                "schedTime": "12:30 PM",
                "dayClass": "fri",
                "monthClass": "mar",
                "priceLow": 206,
                "priceMid": 149,
                "priceHigh": 77,
                "sold": false,
                "opponentShort": "rockets",
                "opponent": "Houston Rockets",
                "giveaway": "0",
                "value": "0",
                "hot": "0",
                "url": "https://www1.ticketmaster.com/event/0F00570CC59D34E9?brand=trailblazers&extcmp=gw505592&wt.mc_id=NBA_TEAM_POR_SINGLE_GAME_TIX",
                "seats": null,
                "trendData": "",
                "dateTbd": false,
                "daysTil": 623,
                "hoursTil": 14964
            },
            {
                "gameNumber": "20TB38",
                "preseason": "0",
                "schedId": "",
                "playoff": "0",
                "schedSort": "20220311",
                "schedDay": "Friday",
                "schedDate": "March 11th, 2022",
                "schedTime": "6:00 PM",
                "dayClass": "fri",
                "monthClass": "mar",
                "priceLow": 123,
                "priceMid": 80,
                "priceHigh": 35,
                "sold": false,
                "opponentShort": "grizzlies",
                "opponent": "Memphis Grizzlies",
                "giveaway": "0",
                "value": "0",
                "hot": "0",
                "url": "https://www1.ticketmaster.com/event/0F00570CC5C13515?brand=trailblazers&extcmp=gw505596&wt.mc_id=NBA_TEAM_POR_SINGLE_GAME_TIX",
                "seats": null,
                "trendData": "",
                "dateTbd": false,
                "daysTil": 623,
                "hoursTil": 14970
            },
            {
                "gameNumber": "20TB33",
                "preseason": "0",
                "schedId": "",
                "playoff": "0",
                "schedSort": "20220311",
                "schedDay": "Friday",
                "schedDate": "March 11th, 2022",
                "schedTime": "7:00 PM",
                "dayClass": "fri",
                "monthClass": "mar",
                "priceLow": 83,
                "priceMid": 58,
                "priceHigh": 28,
                "sold": false,
                "opponentShort": "grizzlies",
                "opponent": "Memphis Grizzlies",
                "giveaway": "0",
                "value": "0",
                "hot": "1",
                "url": "https://www1.ticketmaster.com/event/0F00570CC61B3569?brand=trailblazers&extcmp=gw505591&wt.mc_id=NBA_TEAM_POR_SINGLE_GAME_TIX",
                "seats": null,
                "trendData": "",
                "dateTbd": false,
                "daysTil": 623,
                "hoursTil": 14971
            },
            {
                "gameNumber": "20TB35",
                "preseason": "0",
                "schedId": "",
                "playoff": "0",
                "schedSort": "20220311",
                "schedDay": "Friday",
                "schedDate": "March 11th, 2022",
                "schedTime": "7:00 PM",
                "dayClass": "fri",
                "monthClass": "mar",
                "priceLow": 58,
                "priceMid": 40,
                "priceHigh": 20,
                "sold": false,
                "opponentShort": "timberwolves",
                "opponent": "Minnesota Timberwolves",
                "giveaway": "0",
                "value": "1",
                "hot": "0",
                "url": "https://www1.ticketmaster.com/event/0F00570CC64735B8?brand=trailblazers&extcmp=gw505593&wt.mc_id=NBA_TEAM_POR_SINGLE_GAME_TIX",
                "seats": null,
                "trendData": "",
                "dateTbd": false,
                "daysTil": 623,
                "hoursTil": 14971
            },
            {
                "gameNumber": "20TB36",
                "preseason": "0",
                "schedId": "",
                "playoff": "0",
                "schedSort": "20220311",
                "schedDay": "Friday",
                "schedDate": "March 11th, 2022",
                "schedTime": "7:00 PM",
                "dayClass": "fri",
                "monthClass": "mar",
                "priceLow": 83,
                "priceMid": 62,
                "priceHigh": 29,
                "sold": false,
                "opponentShort": "mavericks",
                "opponent": "Dallas Mavericks",
                "giveaway": "0",
                "value": "0",
                "hot": "0",
                "url": "https://www1.ticketmaster.com/event/0F00570CC61E3571?brand=trailblazers&extcmp=gw505594&wt.mc_id=NBA_TEAM_POR_SINGLE_GAME_TIX",
                "seats": null,
                "trendData": "",
                "dateTbd": false,
                "daysTil": 623,
                "hoursTil": 14971
            },
            {
                "gameNumber": "20TB39",
                "preseason": "0",
                "schedId": "",
                "playoff": "0",
                "schedSort": "20220311",
                "schedDay": "Friday",
                "schedDate": "March 11th, 2022",
                "schedTime": "7:00 PM",
                "dayClass": "fri",
                "monthClass": "mar",
                "priceLow": 83,
                "priceMid": 62,
                "priceHigh": 29,
                "sold": false,
                "opponentShort": "cavaliers",
                "opponent": "Cleveland Cavaliers",
                "giveaway": "0",
                "value": "0",
                "hot": "0",
                "url": "https://www1.ticketmaster.com/event/0F00570CC622357E?brand=trailblazers&extcmp=gw505597&wt.mc_id=NBA_TEAM_POR_SINGLE_GAME_TIX",
                "seats": null,
                "trendData": "",
                "dateTbd": false,
                "daysTil": 623,
                "hoursTil": 14971
            },
            {
                "gameNumber": "20TB40",
                "preseason": "0",
                "schedId": "",
                "playoff": "0",
                "schedSort": "20220311",
                "schedDay": "Friday",
                "schedDate": "March 11th, 2022",
                "schedTime": "7:00 PM",
                "dayClass": "fri",
                "monthClass": "mar",
                "priceLow": 123,
                "priceMid": 80,
                "priceHigh": 35,
                "sold": false,
                "opponentShort": "nuggets",
                "opponent": "Denver Nuggets",
                "giveaway": "0",
                "value": "0",
                "hot": "0",
                "url": "https://www1.ticketmaster.com/event/0F00570CC5C43517?brand=trailblazers&extcmp=gw505598&wt.mc_id=NBA_TEAM_POR_SINGLE_GAME_TIX",
                "seats": null,
                "trendData": "",
                "dateTbd": false,
                "daysTil": 623,
                "hoursTil": 14971
            },
            {
                "gameNumber": "20TB41",
                "preseason": "0",
                "schedId": "",
                "playoff": "0",
                "schedSort": "20220311",
                "schedDay": "Friday",
                "schedDate": "March 11th, 2022",
                "schedTime": "7:00 PM",
                "dayClass": "fri",
                "monthClass": "mar",
                "priceLow": 161,
                "priceMid": 114,
                "priceHigh": 51,
                "sold": false,
                "opponentShort": "clippers",
                "opponent": "Los Angeles Clippers",
                "giveaway": "0",
                "value": "0",
                "hot": "0",
                "url": "https://www1.ticketmaster.com/event/0F00570CC5A034ED?brand=trailblazers&extcmp=gw505599&wt.mc_id=NBA_TEAM_POR_SINGLE_GAME_TIX",
                "seats": null,
                "trendData": "",
                "dateTbd": false,
                "daysTil": 623,
                "hoursTil": 14971
            },
            {
                "gameNumber": "20TB37",
                "preseason": "0",
                "schedId": "",
                "playoff": "0",
                "schedSort": "20220311",
                "schedDay": "Friday",
                "schedDate": "March 11th, 2022",
                "schedTime": "7:30 PM",
                "dayClass": "fri",
                "monthClass": "mar",
                "priceLow": 123,
                "priceMid": 80,
                "priceHigh": 35,
                "sold": false,
                "opponentShort": "jazz",
                "opponent": "Utah Jazz",
                "giveaway": "0",
                "value": "0",
                "hot": "0",
                "url": "https://www1.ticketmaster.com/event/0F00570CC5BD3513?brand=trailblazers&extcmp=gw505595&wt.mc_id=NBA_TEAM_POR_SINGLE_GAME_TIX",
                "seats": null,
                "trendData": "",
                "dateTbd": false,
                "daysTil": 623,
                "hoursTil": 14971
            }
        ]
    }
});